name: YAxisReverser
version: '${project.version}'
main: net.kunmc.lab.yaxisreverser.YAxisReverser
api-version: 1.16
commands:
  yaxisreversal:
    permission: op
    usage: |-
      /yaxisreversal run [distance]
      /yaxisreversal numberOfExecutions [IntegerValue]